# https://docs.lando.dev/

name: dotenv

services:
  php:
    type: php:7.4
    via: cli
    build_as_root:
      - docker-php-ext-enable xdebug
    overrides:
      environment:
        XDEBUG_MODE: coverage

tooling:
  composer:
    service: php
    cmd: composer
